version: "3.7"

x-task: &task
  image: azoff/speedcheck/tasks
  build: tasks
  depends_on:
    - db
  volumes:
    - sqlite:/var/db
    - ./secrets.json:/run/secrets/speedcheck/secrets.json

services:

  db:
    image: azoff/speedcheck/db
    build: db
    command: migrate.sh /var/db/speedcheck.db
    volumes:
      - sqlite:/var/db

  sample_speedtest:
    <<: *task
    command: sample_speedtest.py /var/db/speedcheck.db

  check_sla:
    <<: *task
    command: check_sla.py /var/db/speedcheck.db

volumes:
  sqlite: