version: "3.7"

x-sqlite-volume: &sqlite-volume
  volumes:
    - sqlite:/var/db

x-task: &task
  <<: *sqlite-volume
  image: azoff/speedcheck/tasks
  build: tasks
  depends_on:
    - db

services:

  db:
    <<: *sqlite-volume
    image: azoff/speedcheck/db
    build: db
    command: migrate.sh /var/db/speedcheck.db

  sample_speedtest:
    <<: *task
    command: sample_speedtest.py /var/db/speedcheck.db

  check_sla:
    <<: *task
    command: check_sla.py /var/db/speedcheck.db

volumes:
  sqlite: