version: "3.7"

x-task: &task
  image: azoff/speedcheck/tasks
  build: tasks
  environment:
    - SECRETS_PATH=/run/secrets/speedcheck/secrets.json
  volumes:
    - sqlite:/var/db
    - secrets:/run/secrets

services:

  secrets:
    image: azoff/docker-mount-k8s-secrets:1.1.0
    environment:
      - KUBE_NAMESPACE=speedcheck
    command: secrets=speedcheck

  db:
    image: azoff/speedcheck/db
    build: db
    command: migrate.sh /var/db/speedcheck.db
    volumes:
      - sqlite:/var/db

  sample_speedtest:
    <<: *task
    command: sample_speedtest.py /var/db/speedcheck.db

  check_sla:
    <<: *task
    command: check_sla.py /var/db/speedcheck.db

volumes:
  sqlite:
  secrets: